export const states = [
	{
		id: 3708,
		name: 'Barbuda',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '10',
		type: null,
		latitude: '17.62662420',
		longitude: '-61.77130280',
	},
	{
		id: 3703,
		name: 'Redonda',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '11',
		type: null,
		latitude: '16.93841600',
		longitude: '-62.34551480',
	},
	{
		id: 3709,
		name: 'Saint George Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '03',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 3706,
		name: 'Saint John Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '04',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 3707,
		name: 'Saint Mary Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '05',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 3705,
		name: 'Saint Paul Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '06',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 3704,
		name: 'Saint Peter Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '07',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 3710,
		name: 'Saint Philip Parish',
		country_id: 10,
		country_code: 'AG',
		country_name: 'Antigua and Barbuda',
		state_code: '08',
		type: null,
		latitude: '40.43682580',
		longitude: '-80.06855320',
	},
];
