export const states = [
	{
		id: 5118,
		name: 'Bethlehem',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'BTH',
		type: 'governorate',
		latitude: '31.70539960',
		longitude: '35.19368770',
	},
	{
		id: 5119,
		name: 'Deir El Balah',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'DEB',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5120,
		name: 'Gaza',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'GZA',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5121,
		name: 'Hebron',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'HBN',
		type: 'governorate',
		latitude: '31.53260010',
		longitude: '35.06394750',
	},
	{
		id: 5122,
		name: 'Jenin',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'JEN',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5123,
		name: 'Jericho and Al Aghwar',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'JRH',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5124,
		name: 'Jerusalem',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'JEM',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5125,
		name: 'Khan Yunis',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'KYS',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5126,
		name: 'Nablus',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'NBS',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5127,
		name: 'North Gaza',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'NGZ',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5128,
		name: 'Qalqilya',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'QQA',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5129,
		name: 'Rafah',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'RFH',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5130,
		name: 'Ramallah',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'RBH',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5131,
		name: 'Salfit',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'SLT',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5132,
		name: 'Tubas',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'TBS',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
	{
		id: 5133,
		name: 'Tulkarm',
		country_id: 169,
		country_code: 'PS',
		country_name: 'Palestinian Territory Occupied',
		state_code: 'TKM',
		type: 'governorate',
		latitude: null,
		longitude: null,
	},
];
