export const states = [
	{
		id: 914,
		name: 'Eastern Province',
		country_id: 198,
		country_code: 'SL',
		country_name: 'Sierra Leone',
		state_code: 'E',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 911,
		name: 'Northern Province',
		country_id: 198,
		country_code: 'SL',
		country_name: 'Sierra Leone',
		state_code: 'N',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 912,
		name: 'Southern Province',
		country_id: 198,
		country_code: 'SL',
		country_name: 'Sierra Leone',
		state_code: 'S',
		type: null,
		latitude: null,
		longitude: null,
	},
	{
		id: 913,
		name: 'Western Area',
		country_id: 198,
		country_code: 'SL',
		country_name: 'Sierra Leone',
		state_code: 'W',
		type: null,
		latitude: '40.25459690',
		longitude: '-80.24554440',
	},
];
